# Generated by Django 4.1.3 on 2022-11-25 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculation',
            old_name='calculation_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='calculation',
            old_name='calculation_title',
            new_name='title',
        ),
    ]
