# Generated by Django 4.1.3 on 2022-11-25 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_rename_calculation_date_calculation_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CalculationVariables',
            new_name='Variables',
        ),
    ]
