# Generated by Django 4.1.3 on 2022-11-29 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_remove_variables_id_remove_variables_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variables',
            name='id',
            field=models.BigAutoField(default=2022110249, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='variables',
            name='calculation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.calculation'),
        ),
        migrations.AlterField(
            model_name='variables',
            name='electrical_mobility',
            field=models.FloatField(default=0, verbose_name='dm'),
        ),
        migrations.AlterField(
            model_name='variables',
            name='mass',
            field=models.FloatField(default=0, verbose_name='m'),
        ),
    ]
